### ISSUE TITLE
Pnpm install errors

### ISSUE THREAD

**Issue by ST3A1TH** [Dreamwxve/Nyxia#6]
DragosT@192 ~ % npm i -g pnpm
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/pnpm
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pnpm'
npm error     at async mkdir (node:internal/fs/promises:855:10)
npm error     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:624:20
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/local/lib/node_modules/pnpm'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

npm error A complete log of this run can be found in: /Users/DragosT/.npm/_logs/2024-07-27T09_04_55_679Z-debug-0.log
DragosT@192 ~ % npm i -g pnpm
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/pnpm
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pnpm'
npm error     at async mkdir (node:internal/fs/promises:855:10)
npm error     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:624:20
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/local/lib/node_modules/pnpm'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.

npm error A complete log of this run can be found in: /Users/DragosT/.npm/_logs/2024-07-27T09_04_59_017Z-debug-0.log
DragosT@192 ~ %

**Comment by Dreamwxve** [comment]
try running it in a terminal at root of your machine and try again:
```
npm cache clean -f && npm rebuild && npm i -g pnpm@latest
```

**Comment by ST3A1TH** [comment]
Already tried that, coming out with the same error

**Comment by Dreamwxve** [comment]
can you run this
```
node -v && npm - v
```

**Comment by ST3A1TH** [comment]
DragosT@192 Nyxia-main % node -v && npm - v
v20.14.0
Unknown command: "-"

To see a list of supported npm commands, run:
  npm help

**Comment by Dreamwxve** [comment]
`-v` not `- v` lol

**Comment by ST3A1TH** [comment]
DragosT@192 Nyxia-main % node -v && npm -v 
v20.14.0
10.7.0

**Comment by Dreamwxve** [comment]
Latest versions of node and npm are:
```
Node: v20.15.0
NPM: 10.8.1
```

**Comment by Dreamwxve** [comment]
way to update node is to go here > https://nodejs.org/en (i need to update reminds me)
to update npm:
```
npm i -g npm@latest
```
You can copy the above codeblock too if you hover to the right

**Comment by ST3A1TH** [comment]
Updated!

Same error though:

```
Last login: Sat Jul 27 12:12:06 on ttys004
DragosT@192 Nyxia-main % npm i

up to date, audited 25 packages in 881ms

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
DragosT@192 Nyxia-main % npm i -g pnpm@latest
npm error code EACCES
npm error syscall mkdir
npm error path /usr/local/lib/node_modules/pnpm
npm error errno -13
npm error Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/pnpm'
npm error     at async mkdir (node:internal/fs/promises:858:10)
npm error     at async /usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:624:20
npm error     at async Promise.allSettled (index 0)
npm error     at async [reifyPackages] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:325:11)
npm error     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:142:5)
npm error     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:150:5)
npm error     at async Npm.exec (/usr/local/lib/node_modules/npm/lib/npm.js:207:9)
npm error     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli/entry.js:74:5) {
npm error   errno: -13,
npm error   code: 'EACCES',
npm error   syscall: 'mkdir',
npm error   path: '/usr/local/lib/node_modules/pnpm'
npm error }
npm error
npm error The operation was rejected by your operating system.
npm error It is likely you do not have the permissions to access this file as the current user
npm error
npm error If you believe this might be a permissions issue, please double-check the
npm error permissions of the file and its containing directories, or try running
npm error the command again as root/Administrator.
npm error A complete log of this run can be found in: /Users/DragosT/.npm/_logs/2024-07-27T09_27_20_178Z-debug-0.log
```

**Comment by Dreamwxve** [comment]
hmm this seems to be down to your system itself rather than node or npm. But the package manager used for this project is [`pnpm`](https://pnpm.io/)

**Comment by ST3A1TH** [comment]
dk how it can be system due to it has access to all files it needs so weird

**Comment by Dreamwxve** [comment]
try restarting your device, the error is saying that the process doesnt have permissions to make a directory
